# Generated by Django 5.1.5 on 2025-01-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adddevice', '0002_alter_device_options_device_serial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
