# Generated by Django 5.1.5 on 2025-01-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridges',
            options={'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджи'},
        ),
        migrations.AlterModelOptions(
            name='producermodel',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='cartridge',
            field=models.CharField(max_length=50, unique=True, verbose_name='Картридж'),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.RemoveField(
            model_name='cartridges',
            name='prod_mod',
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_add',
            field=models.CharField(blank=True, max_length=30, verbose_name='ip-адрес'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note',
            field=models.CharField(blank=True, max_length=250, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='prod_mod_dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producermodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, default='s/n', max_length=20, verbose_name='Серийный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='producer_model',
            field=models.CharField(max_length=50, unique=True, verbose_name='Производитель и модель'),
        ),
        migrations.AddField(
            model_name='cartridges',
            name='prod_mod',
            field=models.ManyToManyField(to='main.producermodel', verbose_name='Модель'),
        ),
    ]
