# Generated by Django 5.1.4 on 2025-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cartridges_options_alter_producermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='prod_mod',
            field=models.ManyToManyField(related_name='model', to='main.producermodel', verbose_name='Модель'),
        ),
    ]
