# Generated by Django 5.1.4 on 2025-01-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cartridges_prod_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='prod_mod_dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producermodelset', to='main.producermodel', verbose_name='Модель'),
        ),
    ]
