# Generated by Django 5.1.4 on 2025-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_device_prod_mod_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inv_num',
            field=models.CharField(max_length=15, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
