# Generated by Django 5.1.5 on 2025-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_device_inv_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inv_num',
            field=models.CharField(max_length=15, verbose_name='Инвентарный номер'),
        ),
    ]
