# Generated by Django 5.1.5 on 2025-04-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_device_favorite_userfavoritedevice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='favorite',
        ),
    ]
