# Generated by Django 5.1.5 on 2025-04-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_device_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='describe',
            new_name='description',
        ),
    ]
