# Generated by Django 5.1.4 on 2025-08-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_device_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inv_num',
            field=models.CharField(max_length=17, verbose_name='Инвентарный номер'),
        ),
    ]
